// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.9
// source: flowService.proto

package flowProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 流量上报数据
type FlowReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flows    []*Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`                       //流量信息
	ClientIp string  `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` //客户端IP
	UpTime   int64   `protobuf:"varint,3,opt,name=up_time,json=upTime,proto3" json:"up_time,omitempty"`      //上报时间戳
}

func (x *FlowReport) Reset() {
	*x = FlowReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowReport) ProtoMessage() {}

func (x *FlowReport) ProtoReflect() protoreflect.Message {
	mi := &file_flowService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowReport.ProtoReflect.Descriptor instead.
func (*FlowReport) Descriptor() ([]byte, []int) {
	return file_flowService_proto_rawDescGZIP(), []int{0}
}

func (x *FlowReport) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *FlowReport) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *FlowReport) GetUpTime() int64 {
	if x != nil {
		return x.UpTime
	}
	return 0
}

type Flow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // 账号ID
	CustmerId int64 `protobuf:"varint,2,opt,name=custmer_id,json=custmerId,proto3" json:"custmer_id,omitempty"` // 客户ID
	UpFlow    int64 `protobuf:"varint,3,opt,name=up_flow,json=upFlow,proto3" json:"up_flow,omitempty"`          // 上行流量
}

func (x *Flow) Reset() {
	*x = Flow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_flowService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_flowService_proto_rawDescGZIP(), []int{1}
}

func (x *Flow) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Flow) GetCustmerId() int64 {
	if x != nil {
		return x.CustmerId
	}
	return 0
}

func (x *Flow) GetUpFlow() int64 {
	if x != nil {
		return x.UpFlow
	}
	return 0
}

// 服务端 流量信息GRPC请求参数
type ServerFlowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowDatas *FlowReport `protobuf:"bytes,1,opt,name=flow_datas,json=flowDatas,proto3" json:"flow_datas,omitempty"` // 流量数据
}

func (x *ServerFlowRequest) Reset() {
	*x = ServerFlowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFlowRequest) ProtoMessage() {}

func (x *ServerFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFlowRequest.ProtoReflect.Descriptor instead.
func (*ServerFlowRequest) Descriptor() ([]byte, []int) {
	return file_flowService_proto_rawDescGZIP(), []int{2}
}

func (x *ServerFlowRequest) GetFlowDatas() *FlowReport {
	if x != nil {
		return x.FlowDatas
	}
	return nil
}

// 服务端 全量GRPC响应参数
type ServerFlowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 响应消息
	Result  int32  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`  // 响应结果
}

func (x *ServerFlowResponse) Reset() {
	*x = ServerFlowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFlowResponse) ProtoMessage() {}

func (x *ServerFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flowService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFlowResponse.ProtoReflect.Descriptor instead.
func (*ServerFlowResponse) Descriptor() ([]byte, []int) {
	return file_flowService_proto_rawDescGZIP(), []int{3}
}

func (x *ServerFlowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerFlowResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_flowService_proto protoreflect.FileDescriptor

var file_flowService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69,
	0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x66, 0x6c, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x6c,
	0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x05, 0x66, 0x6c,
	0x6f, 0x77, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x04, 0x46, 0x6c, 0x6f,
	0x77, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x70, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x70, 0x46, 0x6c, 0x6f, 0x77, 0x22, 0x49, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c,
	0x6f, 0x77, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x5e, 0x0a, 0x11, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x49, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x2e, 0x66,
	0x6c, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x6c, 0x6f,
	0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_flowService_proto_rawDescOnce sync.Once
	file_flowService_proto_rawDescData = file_flowService_proto_rawDesc
)

func file_flowService_proto_rawDescGZIP() []byte {
	file_flowService_proto_rawDescOnce.Do(func() {
		file_flowService_proto_rawDescData = protoimpl.X.CompressGZIP(file_flowService_proto_rawDescData)
	})
	return file_flowService_proto_rawDescData
}

var file_flowService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_flowService_proto_goTypes = []interface{}{
	(*FlowReport)(nil),         // 0: flowProto.FlowReport
	(*Flow)(nil),               // 1: flowProto.Flow
	(*ServerFlowRequest)(nil),  // 2: flowProto.ServerFlowRequest
	(*ServerFlowResponse)(nil), // 3: flowProto.ServerFlowResponse
}
var file_flowService_proto_depIdxs = []int32{
	1, // 0: flowProto.FlowReport.flows:type_name -> flowProto.Flow
	0, // 1: flowProto.ServerFlowRequest.flow_datas:type_name -> flowProto.FlowReport
	2, // 2: flowProto.ServerFlowService.SyncFlow:input_type -> flowProto.ServerFlowRequest
	3, // 3: flowProto.ServerFlowService.SyncFlow:output_type -> flowProto.ServerFlowResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flowService_proto_init() }
func file_flowService_proto_init() {
	if File_flowService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flowService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerFlowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerFlowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flowService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flowService_proto_goTypes,
		DependencyIndexes: file_flowService_proto_depIdxs,
		MessageInfos:      file_flowService_proto_msgTypes,
	}.Build()
	File_flowService_proto = out.File
	file_flowService_proto_rawDesc = nil
	file_flowService_proto_goTypes = nil
	file_flowService_proto_depIdxs = nil
}
